apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-daemonset
  labels:
    app: fluent
spec:
  selector:
    matchLabels:
      app: fluent
  template:
    metadata:
      name: fluent-pod
      labels:
        app: fluent
    spec:
      containers:
        - name: fluent-container
          image: fluent/fluentd:v1.14.5-1.1
